name: agrilens_app
description: "AgriLens AI - Smart Farming mobile assistant app for crop disease scanner and farm advisor."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  
  # State management & settings
  provider: ^6.1.2
  shared_preferences: ^2.2.2
  
  # Network & APIs
  http: ^1.2.0
  
  # Device integrations
  camera: ^0.10.5+9
  image_picker: ^1.0.7
  path_provider: ^2.1.2
  
  # Voice integrations
  speech_to_text: ^6.1.1
  flutter_tts: ^3.8.5
  
  # UI Data Visualizations & Maps
  fl_chart: ^0.66.0
  flutter_map: ^6.1.0
  latlong2: ^0.9.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  # Asset assets (such as local model, images/icons, default maps, audio fallback files)
  assets:
    - assets/images/
    - assets/model/
    - assets/audio/
